apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api1-rer-sanita-laemur
  labels:
    app: test-api1-rer-sanita-laemur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api1-rer-sanita-laemur
  template:
    metadata:
      labels:
        app: test-api1-rer-sanita-laemur
    spec:
      containers:
        - name: test-api1-rer-sanita-laemur
          image: python:3
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - mkdir /rer_app;
              cd rer_app/;
              git init;
              git remote add origin https://github.com/mantmarco/test-ico-rer.git;
              git branch -M main;
              git pull origin main;
              python3 test_api.py;
          workingDir: "/"
          ports:
            - containerPort: 8080
